### ISSUE TITLE
Control over service worker

### ISSUE THREAD

**Issue by cernockyd** [next-book/nb-mapper#18]
More control over SW is required so we don’t need to open book in anonymous window to be sure.

Requirements
- when the cache was filled is available via API
- when the service worker was flashed is available via API

**Comment by cernockyd** [comment]
The solution is proposed in eb35bd2. I am about to double check it and submit PR later.  

Service worker saves timestamp of cache deletion and self-activation into IndexedDB and exposes them via messages.

List of allowed messages and result of the messages are exported as types to be reused in interface.

Following messages are available
- `getCacheDeletedAt`
- `getActivatedAt`
- `getServiceWorkerMetadata` - returns object containing both former options

## Example usage

Listen to messages from service worker
```js
navigator.serviceWorker.addEventListener('message', function(event) {
    console.log(event.data);
})
```

Send message to service worker from window
```js
navigator.serviceWorker.controller.postMessage('getServiceWorkerMetadata');
``` 

See the result in console
```js
{
    "success": true,
    "data": {
        "activatedAt": "2021-11-14T20:17:03.736Z"
        "cacheDeletedAt": undefined // does not exist yet
    }
}
```

At this point the information is only via get messages. I am going to add few lines later to ensure service worker sends messages to clients every time a change occurs so its ready for usage in UI.

**Comment by jan-martinek** [comment]
Thanks a lot! 

I have a question and perhaps an addition for the reqs above: Is it possible to flush/reload the cache with the added implementation? I checked the activation handler only briefly, so I’m not sure about it. If not, would it be hard to add?

**Comment by cernockyd** [comment]
Hello. In abd9d6c I’ve just added API for more cache control, namely:

For fresh cache:
- updateCache
  - deletes current cache, creates fresh new one and adds files to it **(this is what you requested)**
  - usage: `navigator.serviceWorker.controller.postMessage({message: 'updateCache');`

I’ve implemented two options to avoid hitting cache altogether: 
- deleteCache
  - deletes current cache, so all upcoming requests are fetched
  - cache is created again by sending `updateCache` message (above) or when service worker activates again.
  - usage: `navigator.serviceWorker.controller.postMessage({message: 'deleteCache'});`
- setIgnoreCache
  - when set to true, skips any cache hit. The cache still lives, is being updated etc. but is ignored and requests are fetch as if the cache didn’t exist.
  - this setting is persistent until you set it back to default value (false).
  - usage: `navigator.serviceWorker.controller.postMessage({message: 'setIgnoreCache', value: true});`
  - to know the current state: `navigator.serviceWorker.controller.postMessage({message: 'getIgnoreCache');`

Then some special ones:
- getMetadata - info from all following api messages
- getCacheExists - boolean indicating whether current cache exist
- deleteOldCache - deletes old cache so the browser doesn’t have to

And corresponding timestamps:
- getActivatedAt
- getOldCacheDeletedAt
- getCacheDeletedAt
- getCacheUpdatedAt

When using post messages like deleteCache or setIgnoreCache, service worker always reacts by sending relevant updated information back. E.g. response to deleteCache is object with cacheDeletedAt timestamp.

**Comment by jan-martinek** [comment]
Whoa, that’s what I call a pleasant overdelivery! 👯

**Comment by cernockyd** [comment]
Message resolving logic is now (355760c) moved into standalone functions in object literal style because it leverages function definition type checking and it is easier to test. Im preparing to test it and submit PR.

**Comment by cernockyd** [comment]
I realised that some reasoning about why I decided to use IndexedDB to store sw-related data could be useful for later, so here are my notes:

We cant rely on global state in service worker, because the next time we would come, the data would be lost and we would probably know that only in production. 

Sw has two options to store persisted data:
- send the data the window and use whatever storage API like localStorage, or save it to DOM 
  - may be handy in case we have robust browser state management/context solution that we want to reuse and leverage
  - adds complexity
- use IndexedDB to save data. IndexedDB is the only accessible API for data storage
  - encapsulates data storage logic into the code of sw
